### ISSUE TITLE
Python bindings do not catch interrupts

### ISSUE THREAD

**Issue by motiwari** [ThrunGroup/BanditPAM#21]
Right now, if we run the code from Python and try to interrupt it with Ctrl+C, nothing happens -- the script continues running, or only kills after a very long time.

Instead, we should modify the code to pass this interrupt / kill signal to the C++ code and kill the computation, so users don't have to wait a long time after pressing Ctrl+C.

**Comment by dhaval737** [comment]
Hi @motiwari  
Is this correct example for this issue?  I basically copied the example2 from the readme and ran the code. I interrupted the code with Ctrl+C.

dhavaldangaria@Dhavals-MacBook-Pro BanditPAM % /usr/local/bin/python3 /Users/dhavaldangaria/BanditPAM/example2.py
^CTraceback (most recent call last):
  File "/Users/dhavaldangaria/BanditPAM/example2.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/rcsetup.py", line 24, in <module>
    from matplotlib import _api, animation, cbook
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/animation.py", line 34, in <module>
    from PIL import Image
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/Image.py", line 109, in <module>
    from . import _imaging as core
KeyboardInterrupt
